project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - lecture01.qmd
    - lecture02.qmd
    - lecture03.qmd
    - lecture04.qmd
    - lecture05.qmd

format:
  revealjs:
    theme: [default, dracula]

